name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_win_extract:
    name: Build on Windows
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2

      - name: Get Qt
        uses: actions/checkout@v2
        with:
          repository: LongSoft/qt-5.6.3-static-x86-msvc2017
          path: qt
          lfs: true
      - name: Unpack Qt
        shell: bash
        working-directory: qt
        run: 7z x qt-5.6.3-static-x86-msvc2017.7z -o../..
      - name: Create dist directory
        shell: bash
        run: mkdir dist

      - name: Create UEFIExtract build directory
        run: cmake -E make_directory ${{runner.workspace}}/build/UEFIExtract
      - name: Configure UEFIExtract
        shell: bash
        working-directory: ${{runner.workspace}}/build/UEFIExtract
        run: cmake -G "Visual Studio 15 2017" -T "v141_xp" -DU_STATIC_RT=YES ../../UEFITool/UEFIExtract/
      - name: Build UEFIExtract
        working-directory: ${{runner.workspace}}/build/UEFIExtract
        shell: bash
        run: cmake --build . --config Release
      - name: Archive UEFIExtract
        working-directory: ${{runner.workspace}}/build/UEFIExtract/Release
        shell: bash
        run: |
          UEFITOOL_VER=$(cat ../../../UEFITool/version.h | grep PROGRAM_VERSION | cut -d'"' -f2 | sed 's/NE alpha /A/') ; \
          7z a ../../../UEFITool/dist/UEFIExtract_NE_${UEFITOOL_VER}_win32.zip UEFIExtract.exe

      - name: Create UEFIFind build directory
        run: cmake -E make_directory ${{runner.workspace}}/build/UEFIFind
      - name: Configure UEFIFind
        shell: bash
        working-directory: ${{runner.workspace}}/build/UEFIFind
        run: cmake -G "Visual Studio 15 2017" -T "v141_xp" -DU_STATIC_RT=YES ../../UEFITool/UEFIFind/
      - name: Build UEFIFind
        working-directory: ${{runner.workspace}}/build/UEFIFind
        shell: bash
        run: cmake --build . --config Release
      - name: Archive UEFIFind
        working-directory: ${{runner.workspace}}/build/UEFIFind/Release
        shell: bash
        run: |
          UEFITOOL_VER=$(cat ../../../UEFITool/version.h | grep PROGRAM_VERSION | cut -d'"' -f2 | sed 's/NE alpha /A/') ; \
          7z a ../../../UEFITool/dist/UEFIFind_NE_${UEFITOOL_VER}_win32.zip UEFIFind.exe

      - name: Create UEFITool build directory
        run: cmake -E make_directory ${{runner.workspace}}/build/UEFITool
      - name: Configure UEFITool
        shell: bash
        working-directory: ${{runner.workspace}}/build/UEFITool
        run: ../../qt-5.6.3-static-x86-msvc2017/bin/qmake.exe ../../UEFITool/UEFITool/
      - name: Build UEFITool
        working-directory: ${{runner.workspace}}/build/UEFITool
        shell: cmd
        run: |
            call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
            nmake release
      - name: Archive UEFITool
        working-directory: ${{runner.workspace}}/build/UEFITool/release
        shell: bash
        run: |
          UEFITOOL_VER=$(cat ../../../UEFITool/version.h | grep PROGRAM_VERSION | cut -d'"' -f2 | sed 's/NE alpha /A/') ; \
          7z a ../../../UEFITool/dist/UEFITool_NE_${UEFITOOL_VER}_win32.zip UEFITool.exe

      - name: Upload to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows builds
          path: dist/*.zip
      - name: Windows to releases
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.zip
          tag: V61
          file_glob: true
